### ISSUE TITLE
Ramp not working with v3

### ISSUE THREAD

**Issue by kjellandrew** [josephdadams/spotify-controller#1]
Currently running:
* Spotify for macOS (Intel) 1.2.14.1149.ga3ae422d. 
* Spotify Controller 0.2.0
* Companion 3.0.0rc2
* MacOS 12.4

Play / Pause works fine, but the volume ramp isn't working for the application.

I have a button with two steps acting as a play ramping volume to 100 on step 1, and ramping down to 0 on step 2.

From the log:
`23.07.02 06:00:59 Surface/Handler/streamdeck:DL31L2A84124: Button 1.3 pressed
23.07.02 06:00:59 Instance/Wrapper/spotify-controller2: Error executing action: action is not defined
23.07.02 06:00:59 Instance/Wrapper/spotify-controller2: Sending: play
23.07.02 06:00:59 Instance/Wrapper/spotify-controller2: Error executing action: action is not defined
23.07.02 06:00:59 Surface/Handler/streamdeck:DL31L2A84124: Button 1.3 released
23.07.02 06:01:08 Surface/Handler/streamdeck:DL31L2A84124: Button 1.3 pressed
23.07.02 06:01:08 Instance/Wrapper/spotify-controller2: Error executing action: action is not defined
23.07.02 06:01:08 Surface/Handler/streamdeck:DL31L2A84124: Button 1.3 released
23.07.02 06:01:13 Instance/Wrapper/spotify-controller2: Sending: pause
23.07.02 06:01:13 Instance/Wrapper/spotify-controller2: Error executing action: action is not defined`

Screenshots:
<img width="1014" alt="Screen Shot 2023-07-02 at 5 58 43 AM" src="https://github.com/josephdadams/spotify-controller/assets/1491220/2ed2f96a-beef-4f8b-8da9-de2f3e1ea04e">
<img width="1001" alt="Screen Shot 2023-07-02 at 5 58 55 AM" src="https://github.com/josephdadams/spotify-controller/assets/1491220/b4573cd0-195a-4025-bb52-f0d7c2b96272">

**Comment by josephdadams** [comment]
It's a companion module bug not a spotify controller problem. However I pushed a module v2.0.1 to companion betas that will fix this
