### ISSUE TITLE
broken or incomplete

### ISSUE THREAD

**Issue by EmChampee** [josephdadams/spotify-controller#10]
<img width="372" alt="Screenshot 2024-10-14 at 8 14 41 am" src="https://github.com/user-attachments/assets/34a0611b-72bb-4c43-ad60-12b6b6e82fc5">
Keeps saying broken and to move to bin

**Comment by josephdadams** [comment]
Which version is this?

**Comment by EmChampee** [comment]
The latest.

Cheers Matt.

**Comment by dstant06** [comment]
I got this same message on the arm64 version on my M2 Air, the intel version installed just fine.

**Comment by JonathanGale** [comment]
Having the same issue.

**Comment by millerzacharys** [comment]
I am also getting the same message when I open on my M1 Mac Mini

**Comment by josephdadams** [comment]
I have released `v1.0.0`, please re open this issue if it persists.
