### ISSUE TITLE
Volume Mute error

### ISSUE THREAD

**Issue by nbrekken** [josephdadams/spotify-controller#2]
Unhandled Error
TypeError: Cannot read property 'volume' of undefined
    at /Applications/Spotify Controller.app/Contents/Resources/app.asar/node_modules/spotify-node-applescript/lib/spotify-node-applescript.js:196:29
    at /Applications/Spotify Controller.app/Contents/Resources/app.asar/node_modules/spotify-node-applescript/lib/spotify-node-applescript.js:100:20
    at ChildProcess.<anonymous> (/Applications/Spotify Controller.app/Contents/Resources/app.asar/node_modules/applescript/lib/applescript.js:54:7)

**Comment by josephdadams** [comment]
What steps did you take to produce this error?

**Comment by nbrekken** [comment]
I added the mute function to a button. It’s the only command. Maybe it’s my version of Spotify? I have the latest version installed. Nathan BrekkenOn Aug 9, 2023, at 9:43 AM, Joseph Adams ***@***.***> wrote:﻿
What steps did you take to produce this error?

**Comment by josephdadams** [comment]
What version of spotify-controller?

**Comment by josephdadams** [comment]
I was able to reproduce it in an earlier version of the program, but in `0.2.0` it mutes/unmutes without issue.

**Comment by nbrekken** [comment]
I have version 0.2.0 of spotify controller.
I have version Spotify for macOS (Apple Silicon)1.2.17.834.g26ee1129
I'm using version 3.0.0+6049-Stable-126f27e8 of Bitfocus Companion
I'm running Ventura 13.4.1 on my Mac
I can try again later today.  Maybe I was doing something wrong.
Nathan Brekken
***@***.***
 

    On Wednesday, August 9, 2023 at 06:17:29 PM MDT, Joseph Adams ***@***.***> wrote:  
 
 


I was able to reproduce it in an earlier version of the program, but in 0.2.0 it mutes/unmutes without issue.

**Comment by nbrekken** [comment]
I was able to test again.  The mute works, but the error pops up when I hit the button.
Nathan ***@***.***
 

    On Wednesday, August 9, 2023 at 06:17:29 PM MDT, Joseph Adams ***@***.***> wrote:  
 
 


I was able to reproduce it in an earlier version of the program, but in 0.2.0 it mutes/unmutes without issue.

**Comment by josephdadams** [comment]
Try the latest release and if this issue still persists, we can revisit this.
