### ISSUE TITLE
Possible bug with: spotify-controller:player_state

### ISSUE THREAD

**Issue by jtylerkelly** [josephdadams/spotify-controller#3]
Hi Joseph - First let me say thanks.... This tool has been a wonderful addition to the tech team and for the volunteers at our church! I just have one recent problem I noticed that I think is a bug, but you can check it out and let me know for sure? 

We use "feedbacks" within companion and for our steam deck. I have a feedback that uses the "$(spotify-controller:player_state)" variable of your tool to check whether Spotify is actually "playing" or if it is "paused" Based on the player-state variable that your tool reports... I then write the text "(playing)" or "(paused)" back to the stream deck button so our volunteers have the assurance that when they pressed the play button on the stream deck for Spotify it actually worked. 

So initially my stream deck buttons just say "Spotify Play" and "Spotify Pause" and when pressed the phrase "(playing)" or "(paused)" gets added as a suffix to the end. I am thinking Spotify recently updated their app? We are running "Spotify for macOS (Intel) 1.2.20.1218.g02aff7a4", and I have updated your Spotify controller to version "0.2.0". The problem still persists but I think it is due to the Spotify app updating?

So the problem....  I first use the "spotify-controller: Ramp Volume" command to ramp the volume to 50% when the play button is pressed on the stream deck. Then after that follows the "spotify-controller: Play" command. When I check the player-state variable after the play command is pressed its still hung on "Ramping Volume to 50", and never reports "Playing" or "Paused" like it used to. Its like I cant get it to report anything but "Ramping Volume to 50"... so I am thinking the player-state variable is not working correctly?

**Comment by josephdadams** [comment]
What version of the Spotify controller module in companion?

**Comment by jtylerkelly** [comment]
techministry-spotifycontroller v1.0.4

**Comment by josephdadams** [comment]
v2.0.1 is the latest… upgrade companion and try it again

**Comment by jtylerkelly** [comment]
Yeah I was worried about upgrading companion to 3.0.1 due to the fact we also use Tech Ministry "Midi-Relay". That did not work right if I remember the last time I upgraded companion months ago... so I downgraded. I will try again though if you think that is best.

**Comment by josephdadams** [comment]
I gave midi-relay an upgrade recently too. I recommend the upgrade.

**Comment by jtylerkelly** [comment]
Thanks… I believe the error I was getting on my Windows machine said
something about socket errors. These errors popped up immediately upon
opening midi-relay and when I pressed ok it immediately shut down the
application.

 If I am already running an earlier version with pm-2 as a service should I
uninstall anything prior to installing the new version of midi-relay?

**Comment by josephdadams** [comment]
Yes you should uninstall the old version.

**Comment by josephdadams** [comment]
Make sure you delay the play or pause command so that it runs after the volume has finished ramping. Otherwise they will run simultaneously.
