### ISSUE TITLE
Ramp Volume Ideas

### ISSUE THREAD

**Issue by nickwarr167** [josephdadams/spotify-controller#4]
Hi Joseph. I'm currently building out my stream deck workflow for live events, and your work has been super helpful!

I'd like to suggest a couple tweaks, if I can. I'm using the rampVolume function to fade in/out the music. I'd like to be able to fade out the music before the initial fade-in is completed (Just in case of a mistaken button press or quick turnaround). As it stands, that causes some issues with the controller. If more than one ramp is going at once, the volume jumps all around as the ramps compete with each other. Is there any way you can make it so only the most recent rampVolume continues, while previous ones are abandoned? Or, at least, one cannot begin before the other has ended?

Additionally, would it be possible to make the ramp time user-definable in companion? Currently, each step is about 0.25s, so the ramp time changes depending on how far there is to go. I'd love to be able to define a total time and have the steps equally spaced within that time frame.

Thanks!
-Nick

**Comment by josephdadams** [comment]
Great ideas! I will see what I can implement sometime.

**Comment by josephdadams** [comment]
v0.3.0 has these ramping improvements!
