### ISSUE TITLE
No variable data returned to companion

### ISSUE THREAD

**Issue by DBinNYC** [josephdadams/spotify-controller#5]
Play, pause, volume up etc work fine,  but the presets return no value. Controller v 0.2.0. 

Spotify: Spotify for macOS (Apple Silicon)
1.2.24.756.g7a7fc7f0

**Comment by josephdadams** [comment]
Meaning the variables are all blank?

**Comment by DBinNYC** [comment]
Pretty much. Not returning anything about current track playing. The transport controls work as mentioned, but no dynamic data is available.

![screencapture-127-0-0-1-8888-buttons-2023-11-19-09_27_54](https://github.com/josephdadams/spotify-controller/assets/59796855/c3c2b1e3-9799-44c6-b7e0-070a089532f1)

**Comment by mikecreates86** [comment]
Seconding this issue. There is and has been an issue with this for some time. Companion can't get the majority of this dynamic data from the helper app.

**Comment by josephdadams** [comment]
<img width="711" alt="Screenshot 2024-01-08 at 3 30 31 PM" src="https://github.com/josephdadams/spotify-controller/assets/2559091/b97c7bce-94c0-467b-9917-85286210b273">

Interesting. It is working for me.

**Comment by josephdadams** [comment]
Try the latest release and if you are still seeing this issue, we can revisit. But I am not seeing it on my end.
