### ISSUE TITLE
Volume control not working

### ISSUE THREAD

**Issue by haffitempo** [josephdadams/spotify-controller#6]
Volume control is not working for me.  Is this a bug - or needs more config ?

**Comment by josephdadams** [comment]
Maybe clarify more about how you are using the program. Rest api? Socketio? (The companion module uses socketio.) what version of Spotify controller?

**Comment by josephdadams** [comment]
What version of the companion module and what version of Spotify controller?

**Comment by haffitempo** [comment]
Companion [3.2.1 (3.2.1+6676-stable-fa981d25)](https://bitfocus.io/companion/)
Controller 0.3.0

**Comment by josephdadams** [comment]
Click the ? Icon next to the module instance in companion. It will report the module version.

**Comment by haffitempo** [comment]
Spotify Controller v2.0.1
this ?

**Comment by josephdadams** [comment]
The latest version should be v2.1.0. So download a beta build of companion and try to recreate this issue again. If it still happens you can re open this issue.

**Comment by haffitempo** [comment]
Ok - Thanx
