### ISSUE TITLE
Connection issues

### ISSUE THREAD

**Issue by EventeQ** [josephdadams/spotify-controller#7]
Hi Joseph

I have just installed this module in one of my older mac mini (2014 model, i5 2,6ghz 8gb ram) and this machine runs OS X 12.7.3 (Monterey), and it seem to have an issue with my connection to companion (3.1.2 build).
I use the 0.3.0 version of your controller module. 
It is the latest version of spotify, fresh installation.

I have spotify, stage timer and playback pro on this machine and every module works with zero latency from companion and any of my streamdecks in this system except the spotify controller module.
It loose connection and if I press button nothing happens, and then a short while later all commands that I did but never happened - all of them comes at the same time upon getting connection before connection goes idle again. 
It is like I have connection on/off back and forth and it is only doing this with your spotify module and not the other 2 in use, these work when the controller doesn't.
Also as soon as I hover my mouse pointer above your icon in the top meny I get the spinning color disk and I just simply can not do anything with the controller settings.

I just can't figure this out no matter what I do atm, any advice would be highly appreciated.

**Comment by josephdadams** [comment]
It sounds like the program is hanging up and not able to execute the AppleScript commands (the underlying functionality to control the Spotify app)

**Comment by EventeQ** [comment]
> It sounds like the program is hanging up and not able to execute the AppleScript commands (the underlying functionality to control the Spotify app)

I personally know nothing about programming so I dont know really. Is there anything I can do to troubleshoot in a way that will help you get the right info so this can be resolved?

**Comment by josephdadams** [comment]
Do you have any other MacOS Monterey computers you could test on?

**Comment by EventeQ** [comment]
Acctually I do. 
I have my old retina which is on Mojave atm, I will update it to monterey 12.7.4 and get back to you after I made some tests.
I will also update the mini from 12.7.3 to 12.7.4 to see if anything changes.

I will get back to you regarding this after both machines are on the same OS verision.
Don't know if it is helpful but I links to both macs specs below 

Mini
https://everymac.com/systems/apple/mac_mini/specs/mac-mini-core-i5-2.6-late-2014-specs.html

Retina
https://everymac.com/systems/apple/macbook_pro/specs/macbook-pro-core-i7-2.5-15-dual-graphics-mid-2015-retina-display-specs.html

**Comment by EventeQ** [comment]
So I left the retina running and now some time after I get error message that states:

TypeError: Cannot read property 'volume' of undefined
at /Applications/Spotify Controller.app/Contents/Resources/app.asar/node_modules/spotify-node-applescript/lib/spotify-node-applescript.js:196:29
at /Applications/Spotify Controller.app/Contents/Resources/app.asar/node_modules/spotify-node-applescript/lib/spotify-node-applescript.js:100:20
at ChildProcess.<anonymous> (/Applications/Spotify Controller.app/Contents/Resources/app.asar/node_modules/applescript/lib/applescript.js:54:7)

**Comment by EventeQ** [comment]
So I did as you suggested, no error message yet but activity monitor shows that it is unresponsive. Leaving it as it is and maybe I get an error message on both machines.

Also, if I start the controller, then start spotify and then activate the controller in companion I get unresponsive state in Activity Monitor

**Comment by josephdadams** [comment]
Try latest release and re open issue if needed
