### ISSUE TITLE
Volume Up & Down

### ISSUE THREAD

**Issue by EmChampee** [josephdadams/spotify-controller#8]
I can't seem to get the vol up & down working, everything else works though.

Working on a M3MAX  Sonoma 14.5. running companion & streamdeck

**Comment by josephdadams** [comment]
What version of Spotify controller? What version of the Spotify controller module in companion?

**Comment by EmChampee** [comment]
0.3.0 Spotify Controller
Spotify Controller v2.0.1 - Companion module

**Comment by jwetzell** [comment]
I see the same thing happening with 0.3.0, it looks like it is a result of the way electron is packaging the files and how `spotify-node-applescript` is referencing files using `__dirname` as all the commands that are loaded from files through errors that the applescript file it is looking for cannot be found.

**Comment by josephdadams** [comment]
v0.3.1 includes this fix
